In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [17]:
data = pd.read_csv("pet_health_records.csv")

In [18]:
# One-hot encode breed
data = pd.get_dummies(data, columns=["breed"])

In [19]:
# Encode disease
le = LabelEncoder()
data["disease"] = le.fit_transform(data["disease"])

In [20]:
X = data.drop("disease", axis=1)
y = data["disease"]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [22]:
modelR = RandomForestClassifier(
    n_estimators=500,
    max_depth=None,
    class_weight="balanced",  # 🔥 IMPORTANT
    random_state=42
)

In [23]:
modelR.fit(X_train, y_train)

,n_estimators,500
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [24]:
y_pred = modelR.predict(X_test)

In [25]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9


In [26]:
# Precision
print("Precision (Weighted):", precision_score(y_test, y_pred, average='weighted'))

Precision (Weighted): 0.9027777777777778


In [27]:
# Recall
print("Recall (Weighted):", recall_score(y_test, y_pred, average='weighted'))

Recall (Weighted): 0.9


In [28]:
# F1 Score
print("F1 Score (Weighted):", f1_score(y_test, y_pred, average='weighted'))

F1 Score (Weighted): 0.898989898989899


In [29]:
# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       0.75      0.60      0.67        20
           2       0.67      0.80      0.73        20
           3       1.00      1.00      1.00        20
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20

    accuracy                           0.90       120
   macro avg       0.90      0.90      0.90       120
weighted avg       0.90      0.90      0.90       120



In [30]:
# Confusion Matrix
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:

[[20  0  0  0  0  0]
 [ 0 12  8  0  0  0]
 [ 0  4 16  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 20  0]
 [ 0  0  0  0  0 20]]


In [31]:
from xgboost import XGBClassifier

In [32]:
modelXB = XGBClassifier(
    n_estimators=600,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)

In [33]:
modelXB.fit(X_train, y_train)

,objective,'multi:softprob'
,base_score,None
,booster,None
,callbacks,None
,colsample_bylevel,None
,colsample_bynode,None
,colsample_bytree,0.9
,device,None
,early_stopping_rounds,None
,enable_categorical,False
,eval_metric,None


In [14]:
print("Accuracy:", accuracy_score(y_test, modelXB.predict(X_test)))

Accuracy: 0.875


In [40]:
# Precision (weighted)
print("Precision (Weighted):", precision_score(y_test, modelXB.predict(X_test), average='weighted'))

Precision (Weighted): 0.8759590792838875


In [41]:
# Recall (weighted)
print("Recall (Weighted):", recall_score(y_test, modelXB.predict(X_test), average='weighted'))

Recall (Weighted): 0.875


In [42]:
# F1 Score (weighted)
print("F1 Score (Weighted):", f1_score(y_test, modelXB.predict(X_test), average='weighted'))

F1 Score (Weighted): 0.8742928975487115


In [43]:
# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, modelXB.predict(X_test)))


Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       0.65      0.55      0.59        20
           2       0.61      0.70      0.65        20
           3       1.00      1.00      1.00        20
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20

    accuracy                           0.88       120
   macro avg       0.88      0.88      0.87       120
weighted avg       0.88      0.88      0.87       120



In [44]:
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, modelXB.predict(X_test)))


Confusion Matrix:

[[20  0  0  0  0  0]
 [ 0 11  9  0  0  0]
 [ 0  6 14  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 20  0]
 [ 0  0  0  0  0 20]]


In [45]:
import joblib

In [46]:
joblib.dump(modelR, "disease_predictor.pkl")

['disease_predictor.pkl']

In [47]:
joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']

In [48]:
joblib.dump(X.columns.tolist(), "model_columns.pkl")

['model_columns.pkl']